<a href="https://colab.research.google.com/github/rocioblivingston/Data-Analitycs-Python-1C2026/blob/main/Pre_Entrega_Data_Analitycs_C12026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **🏗️ Etapa 1: Recopilación y Preparación de Datos**

**1. Carga de Datasets 📥**
Se procede con la importación de las librerías necesarias (**pandas, numpy**) y la carga de los archivos fuente en formato CSV para su transformación en objetos Dataframe.

In [19]:
# Importa la librería Pandas
import pandas as pd

In [16]:
# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 1. Definir las rutas (Paths) de forma coherente
path_clientes  = '/content/drive/MyDrive/Colab Notebooks/Data Analytics 2026/Pre Entrega/DataSets/Copia de clientes.csv'
path_marketing = '/content/drive/MyDrive/Colab Notebooks/Data Analytics 2026/Pre Entrega/DataSets/Copia de marketing.csv'
path_ventas    = '/content/drive/MyDrive/Colab Notebooks/Data Analytics 2026/Pre Entrega/DataSets/Copia de ventas.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**DataFrame de Clientes**

In [23]:
# 2. Cargar los DataFrames
df_clientes  = pd.read_csv(path_clientes)
df_clientes.head()

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

**DataFrame de Ventas**

In [24]:
df_ventas  = pd.read_csv(path_ventas)
df_ventas.head()

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

**DataFrame Marketing**

In [26]:
df_marketing  = pd.read_csv(path_marketing)
df_marketing.head()

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

##

## **📈 Análisis Exploratorio: Estructura y Dimensiones 📋**

En esta etapa, realizamos una primera aproximación a los conjuntos de datos de **Ventas, Marketing y Clientes**. El objetivo es validar la integridad de la carga desde Google Drive y obtener una visión panorámica de las variables, tipos de datos y la distribución inicial de la información.

In [50]:
datasets = {
    "Ventas": df_ventas,
    "Marketing": df_marketing,
    "Clientes": df_clientes
}

for nombre, df in datasets.items():
    print(f"{'='*30}")
    print(f"📊 DATASET: {nombre.upper()}")
    print(f"{'='*30}")

    # Introducción a Pandas: Análisis exploratorio inicial
    print("\n🔹 Estructura y Dimensiones")
    print(f"📏 El dataset tiene {df.shape[0]} filas y {df.shape[1]} columnas.")


    print("-" * 40)
    print("\n🔹 Tipos de Datos")
    print(df.dtypes)

    print("-" * 40)
    print("\n🔹 Primeros Registros")
    display(df.head(5))

    print("\n📈 Estadísticas descriptivas")
    print(df.describe(include='number'))
    print("-" * 40)

    print("\n📈 Estadísticas descriptivas")

    try:
        print(df.describe(include='object'))
    except:
      print("No hay variables categóricas")



    # Calidad de Datos: Identificación de nulos y duplicados
    print("-" * 40)
    print("\n🔹 Diagnóstico de Calidad de Datos")

    # Identificación de nulos
    nulos = df.isnull().sum()
    if nulos.sum() > 0:
        print(f"⚠️ Valores nulos detectados por columna:\n{nulos[nulos > 0]}")
    else:
        print("✅ No se detectaron valores nulos.")
        print("-" * 40)

    print("📌 Porcentaje de nulos por columna %")
    porcentaje_nulos = df.isnull().mean() * 100
    if (porcentaje_nulos > 0).any():
        print(porcentaje_nulos[porcentaje_nulos > 0].sort_values(ascending=False))
    else:
        print("No hay valores nulos (0% en todas las columnas)")
    print("-" * 40)

    # Identificar duplicados
    duplicados = df.duplicated().sum()
    print(f"🔁 Cantidad de registros duplicados: {duplicados}")

    print("\n" + "—"*50 + "\n")

==============================
📊 DATASET: VENTAS
==============================

🔹 Estructura y Dimensiones
📏 El dataset tiene 3035 filas y 6 columnas.
----------------------------------------

🔹 Tipos de Datos
id_venta         int64
producto        object
precio          object
cantidad       float64
fecha_venta     object
categoria       object
dtype: object
----------------------------------------

🔹 Primeros Registros

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

📈 Estadísticas descriptivas
          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000
----------------------------------------

📈 Estadísticas descriptivas
               producto  precio fecha_venta   categoria
count              3035    3033        3035        3035
unique               30    2590         364           3
top     Lámpara de mesa  $76.32  06/04/2024  Decoración
freq                181       5          24        1015
----------------------------------------

🔹 Diagnóstico de Calidad de Datos
⚠️ Valores nulos detectados por columna:
precio      2
cantidad    2
dtype: int64
📌 Porcentaje de nulos por columna %
precio      0.065898
cantidad    0.065898
dtype: float64
----------------------------------------
🔁 Cantidad de registros duplicados: 35

——————————————————————————————————————————————————

==============================
📊 DATASET: MARKETING
==============================

🔹 Estructura y Dimensiones
📏 El dataset tiene 90 filas y 6 columnas.
----------------------------------------

🔹 Tipos de Datos
id_campanha       int64
producto         object
canal            object
costo           float64
fecha_inicio     object
fecha_fin        object
dtype: object
----------------------------------------

🔹 Primeros Registros

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

📈 Estadísticas descriptivas
       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000
----------------------------------------

📈 Estadísticas descriptivas
               producto canal fecha_inicio   fecha_fin
count                90    90           90          90
unique               30     3           78          78
top     Adorno de pared    TV   25/09/2024  05/05/2024
freq                  3    30            2           3
----------------------------------------

🔹 Diagnóstico de Calidad de Datos
✅ No se detectaron valores nulos.
----------------------------------------
📌 Porcentaje de nulos por columna %
No hay valores nulos (0% en todas las columnas)
----------------------------------------
🔁 Cantidad de registros duplicados: 0

——————————————————————————————————————————————————

==============================
📊 DATASET: CLIENTES
==============================

🔹 Estructura y Dimensiones
📏 El dataset tiene 567 filas y 5 columnas.
----------------------------------------

🔹 Tipos de Datos
id_cliente      int64
nombre         object
edad            int64
ciudad         object
ingresos      float64
dtype: object
----------------------------------------

🔹 Primeros Registros

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

📈 Estadísticas descriptivas
       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000
----------------------------------------

📈 Estadísticas descriptivas
             nombre         ciudad
count           567            567
unique          567             12
top     Micah Matis  Mar del Plata
freq              1             63
----------------------------------------

🔹 Diagnóstico de Calidad de Datos
✅ No se detectaron valores nulos.
----------------------------------------
📌 Porcentaje de nulos por columna %
No hay valores nulos (0% en todas las columnas)
----------------------------------------
🔁 Cantidad de registros duplicados: 0

——————————————————————————————————————————————————

***Documentación del Estado Inicial:***

***Ventas:*** Se identificaron registros duplicados que serán eliminados para evitar sesgos en el cálculo de ingresos.

***Clientes/Marketing:*** El dataset se encuentra íntegro en cuanto a valores nulos, permitiendo una integración directa en la **Etapa 2.**

## **🛠️ 5. Calidad de Datos: Diagnóstico de Integridad**

En este apartado, ejecutamos un análisis exhaustivo sobre los DataFrames de Ventas, Marketing y Clientes. El objetivo es identificar valores nulos (missing values) y registros duplicados para documentar el estado inicial de la información, cumpliendo con los estándares de auditoría de datos requeridos en la cursada.

## **👤 EDA Clientes**